name: update README
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: hongyiheng
          svg_out_path: github-contribution-grid-snake.svg
